In [2]:
pip install pandas numpy matplotlib seaborn scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abish\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp314-cp314-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\abish\appdata\roaming\python\python314\site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\abish\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 963.1 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.9 MB 963.1 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.9 MB 963.1 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.9 MB 963.1 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.9 MB 963.1 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.9 MB 963.1 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.9 MB 963.1 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.9 MB 963.1 kB/s eta 0:00:10
   ------ --------------------------------- 1.6/9.9 MB 603.7 kB/s eta 0:00:14
   ------- -------------------------------- 1.8/9.9 MB 649.1 kB/s eta 0:00:13
   ------- -------------------------------- 1.8/9.9 MB 649.1 kB/s eta 0:00:13
   -------- ------------------------------- 2.1/9.9 MB 668.7 kB/s eta 0:00:12
   --------- ------------------------------ 2.4/9.9 MB 705.0 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/9.9 MB 736.9 kB/s eta 0:00:10
   ----------- ---------------------------- 2.9/9.9 MB 764.5 kB/s eta 0:00:10
   ------------ --------------------------- 3.1/9.9 MB 775.6 kB/s eta 0:00:09
   ------------- -------------------------- 3.4/9.9 MB 796.3 kB/s eta 0:00:09
   -------------- ------------------------- 3.7/9.9 MB 815.1 kB/s eta 0:00:08
   --------------- ------------------------ 3.9/9.9 MB 850.8 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.9 MB 854.1 kB/s eta 0:00:07
   ------------------- -------------------- 4.7/9.9 MB 936.3 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.9 MB 998.3 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.9 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 1.2 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.2 MB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 1.3 MB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 1.4 MB/s  0:00:07
Downloading numpy-2.4.3-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 4.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.4 MB 3.0 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.4 MB 3.0 MB/s eta 0:00:04
   ------- -------------------------------- 2.4/12.4 MB 2.7 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.4 MB 2.6 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/12.4 MB 2.5 MB/s eta 0:00:04
   ---------- ----------------------------- 3.1/12.4 MB 2.1 MB/s eta 0:00:05
   ---------- ----------------------------- 3.1/12.4 MB 2.1 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.4 MB 1.9 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.4 MB 1.8 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.4 MB 1.8 MB/s eta 0:00:05
   -------------- ------------------------- 4.5/12.4 MB 1.8 MB/s eta 0:00:05
   --------------- ------------------------ 4.7/12.4 MB 1.8 MB/s eta 0:00:05
   ---------------- ----------------------- 5.2/12.4 MB 1.7 MB/s eta 0:00:05
   ----------------- ---------------------- 5.5/12.4 MB 1.8 MB/s eta 0:00:04
   ------------------- -------------------- 6.0/12.4 MB 1.8 MB/s eta 0:00:04
   -------------------- ------------------- 6.3/12.4 MB 1.8 MB/s eta 0:00:04
   --------------------- ------------------ 6.8/12.4 MB 1.8 MB/s eta 0:00:04
   ----------------------- ---------------- 7.3/12.4 MB 1.8 MB/s eta 0:00:03
   ------------------------ --------------- 7.6/12.4 MB 1.8 MB/s eta 0:00:03
   -------------------------- ------------- 8.1/12.4 MB 1.8 MB/s eta 0:00:03
   --------------------------- ------------ 8.7/12.4 MB 1.9 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.4 MB 1.9 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 2.0 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.4 MB 2.1 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.4 MB 2.0 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.4 MB 1.9 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 1.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 1.6 MB/s  0:00:07
Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.3 MB 3.0 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/8.3 MB 2.9 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.3 MB 2.6 MB/s eta 0:00:03
   ---------- ----------------------------- 2.1/8.3 MB 2.7 MB/s eta 0:00:03
   ------------- -------------------------- 2.9/8.3 MB 2.9 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.3 MB 2.8 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.3 MB 2.8 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.3 MB 2.4 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.3 MB 2.5 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.3 MB 2.6 MB/s eta 0:00:02
   --------------------------- ------------ 5.8/8.3 MB 2.6 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.3 MB 2.6 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.3 MB 2.6 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.3 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.3 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 2.1 MB/s  0:00:03
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 3.3 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.1 MB 4.0 MB/s eta 0:00:02
   ---------- ----------------------------- 2.1/8.1 MB 3.8 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.1 MB 4.0 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.1 MB 4.0 MB/s eta 0:00:02
   ------------------ --------------------- 3.7/8.1 MB 2.9 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.1 MB 2.8 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.1 MB 2.9 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.1 MB 2.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.1 MB 2.6 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.1 MB 2.6 MB/s eta 0:00:01
   ------------------------------- -------- 6.3/8.1 MB 2.6 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.1 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 2.6 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 2.6 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 2.3 MB/s  0:00:03
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ------------- -------------------------- 0.8/2.3 MB 2.3 MB/s eta 0:00:01
   ---------------------- ----------------- 1.3/2.3 MB 2.9 MB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 690.5 kB/s  0:00:03
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.1.1-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.2 MB 2.7 MB/s eta 0:00:03
   ---- ----------------------------------- 0.8/7.2 MB 2.3 MB/s eta 0:00:03
   ------- -------------------------------- 1.3/7.2 MB 2.1 MB/s eta 0:00:03
   -------- ------------------------------- 1.6/7.2 MB 1.8 MB/s eta 0:00:04
   ---------- ----------------------------- 1.8/7.2 MB 1.8 MB/s eta 0:00:04
   ------------- -------------------------- 2.4/7.2 MB 1.9 MB/s eta 0:00:03
   ---------------- ----------------------- 2.9/7.2 MB 2.0 MB/s eta 0:00:03
   ------------------ --------------------- 3.4/7.2 MB 2.0 MB/s eta 0:00:02
   -------------------- ------------------- 3.7/7.2 MB 2.0 MB/s eta 0:00:02
   --------------------- ------------------ 3.9/7.2 MB 2.0 MB/s eta 0:00:02
   ------------------------ --------------- 4.5/7.2 MB 2.0 MB/s eta 0:00:02
   -------------------------- ------------- 4.7/7.2 MB 2.0 MB/s eta 0:00:02
   --------------------------- ------------ 5.0/7.2 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 5.2/7.2 MB 1.8 MB/s eta 0:00:02
   ------------------------------ --------- 5.5/7.2 MB 1.8 MB/s eta 0:00:01
   --------------------------------- ------ 6.0/7.2 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.2 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 1.3 MB/s  0:00:05
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
   -- ------------------------------------- 2.1/37.3 MB 2.7 MB/s eta 0:00:13
   -- ------------------------------------- 2.6/37.3 MB 3.0 MB/s eta 0:00:12
   --- ------------------------------------ 2.9/37.3 MB 2.7 MB/s eta 0:00:13
   --- ------------------------------------ 3.7/37.3 MB 2.8 MB/s eta 0:00:13
   ---- ----------------------------------- 3.9/37.3 MB 2.6 MB/s eta 0:00:13
   ---- ----------------------------------- 4.5/37.3 MB 2.5 MB/s eta 0:00:14
   ----- ---------------------------------- 4.7/37.3 MB 2.3 MB/s eta 0:00:15
   ----- ---------------------------------- 5.0/37.3 MB 2.2 MB/s eta 0:00:15
   ----- ---------------------------------- 5.5/37.3 MB 2.3 MB/s eta 0:00:14
   ------ --------------------------------- 5.8/37.3 MB 2.3 MB/s eta 0:00:14
   ------ --------------------------------- 6.3/37.3 MB 2.2 MB/s eta 0:00:15
   ------- -------------------------------- 6.8/37.3 MB 2.2 MB/s eta 0:00:14
   ------- -------------------------------- 7.3/37.3 MB 2.2 MB/s eta 0:00:14
   -------- ------------------------------- 7.9/37.3 MB 2.2 MB/s eta 0:00:14
   -------- ------------------------------- 8.1/37.3 MB 2.2 MB/s eta 0:00:13
   -------- ------------------------------- 8.1/37.3 MB 2.2 MB/s eta 0:00:13
   ---------- ----------------------------- 10.0/37.3 MB 2.4 MB/s eta 0:00:12
   ----------- ---------------------------- 10.5/37.3 MB 2.4 MB/s eta 0:00:11
   ----------- ---------------------------- 11.0/37.3 MB 2.5 MB/s eta 0:00:11
   ------------ --------------------------- 11.3/37.3 MB 2.4 MB/s eta 0:00:11
   ------------ --------------------------- 11.5/37.3 MB 2.3 MB/s eta 0:00:12
   ------------ --------------------------- 11.8/37.3 MB 2.3 MB/s eta 0:00:11
   ------------- -------------------------- 12.3/37.3 MB 2.3 MB/s eta 0:00:11
   ------------- -------------------------- 12.6/37.3 MB 2.3 MB/s eta 0:00:11
   -------------- ------------------------- 13.4/37.3 MB 2.3 MB/s eta 0:00:11
   -------------- ------------------------- 13.9/37.3 MB 2.3 MB/s eta 0:00:11
   --------------- ------------------------ 14.4/37.3 MB 2.3 MB/s eta 0:00:10
   --------------- ------------------------ 14.7/37.3 MB 2.3 MB/s eta 0:00:10
   ---------------- ----------------------- 14.9/37.3 MB 2.3 MB/s eta 0:00:10
   ---------------- ----------------------- 15.2/37.3 MB 2.2 MB/s eta 0:00:10
   ----------------- ---------------------- 16.0/37.3 MB 2.2 MB/s eta 0:00:10
   ----------------- ---------------------- 16.5/37.3 MB 2.3 MB/s eta 0:00:10
   ----------------- ---------------------- 16.5/37.3 MB 2.3 MB/s eta 0:00:10
   ----------------- ---------------------- 16.5/37.3 MB 2.3 MB/s eta 0:00:10
   ----------------- ---------------------- 16.5/37.3 MB 2.3 MB/s eta 0:00:10
   ----------------- ---------------------- 16.5/37.3 MB 2.3 MB/s eta 0:00:10
   -------------------- ------------------- 19.1/37.3 MB 2.3 MB/s eta 0:00:08
   --------------------- ------------------ 19.9/37.3 MB 2.3 MB/s eta 0:00:08
   --------------------- ------------------ 20.4/37.3 MB 2.3 MB/s eta 0:00:08
   ---------------------- ----------------- 20.7/37.3 MB 2.3 MB/s eta 0:00:08
   ---------------------- ----------------- 21.2/37.3 MB 2.3 MB/s eta 0:00:07
   ----------------------- ---------------- 21.8/37.3 MB 2.3 MB/s eta 0:00:07
   ----------------------- ---------------- 22.3/37.3 MB 2.3 MB/s eta 0:00:07
   ------------------------ --------------- 22.8/37.3 MB 2.3 MB/s eta 0:00:07
   ------------------------- -------------- 23.3/37.3 MB 2.3 MB/s eta 0:00:06
   ------------------------- -------------- 23.9/37.3 MB 2.3 MB/s eta 0:00:06
   -------------------------- ------------- 24.4/37.3 MB 2.3 MB/s eta 0:00:06
   -------------------------- ------------- 24.6/37.3 MB 2.3 MB/s eta 0:00:06
   -------------------------- ------------- 24.9/37.3 MB 2.3 MB/s eta 0:00:06
   --------------------------- ------------ 25.4/37.3 MB 2.3 MB/s eta 0:00:06
   --------------------------- ------------ 25.7/37.3 MB 2.3 MB/s eta 0:00:06
   --------------------------- ------------ 26.0/37.3 MB 2.3 MB/s eta 0:00:05
   ---------------------------- ----------- 26.2/37.3 MB 2.3 MB/s eta 0:00:05
   ---------------------------- ----------- 26.5/37.3 MB 2.2 MB/s eta 0:00:05
   ---------------------------- ----------- 27.0/37.3 MB 2.2 MB/s eta 0:00:05
   ----------------------------- ---------- 27.8/37.3 MB 2.2 MB/s eta 0:00:05
   ------------------------------ --------- 28.3/37.3 MB 2.3 MB/s eta 0:00:04
   ------------------------------ --------- 28.8/37.3 MB 2.3 MB/s eta 0:00:04
   ------------------------------- -------- 29.4/37.3 MB 2.3 MB/s eta 0:00:04
   ------------------------------- -------- 29.6/37.3 MB 2.3 MB/s eta 0:00:04
   -------------------------------- ------- 30.1/37.3 MB 2.3 MB/s eta 0:00:04

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"C:\Users\abish\Downloads\heart_disease_uci.csv")
print(df.head())

   id  age     sex    dataset               cp  trestbps   chol    fbs  \
0   1   63    Male  Cleveland   typical angina     145.0  233.0   True
1   2   67    Male  Cleveland     asymptomatic     160.0  286.0  False
2   3   67    Male  Cleveland     asymptomatic     120.0  229.0  False
3   4   37    Male  Cleveland      non-anginal     130.0  250.0  False
4   5   41  Female  Cleveland  atypical angina     130.0  204.0  False

          restecg  thalch  exang  oldpeak        slope   ca  \
0  lv hypertrophy   150.0  False      2.3  downsloping  0.0
1  lv hypertrophy   108.0   True      1.5         flat  3.0
2  lv hypertrophy   129.0   True      2.6         flat  2.0
3          normal   187.0  False      3.5  downsloping  0.0
4  lv hypertrophy   172.0  False      1.4    upsloping  0.0

                thal  num
0       fixed defect    0
1             normal    2
2  reversable defect    1
3             normal    0
4             normal    0

In [5]:
df.head(5)

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    str
 3   dataset   920 non-null    str
 4   cp        920 non-null    str
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    str
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    str
 13  ca        309 non-null    float64
 14  thal      434 non-null    str
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(2), str(6)
memory usage: 115.1+ KB

In [7]:
df.columns

Index(['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='str')

In [8]:
df.describe()

,id,age,trestbps,chol,thalch,oldpeak,ca,num
count,920.000000,920.000000,861.000000,890.000000,865.000000,858.000000,309.000000,920.000000
mean,460.500000,53.510870,132.132404,199.130337,137.545665,0.878788,0.676375,0.995652
std,265.725422,9.424685,19.066070,110.780810,25.926276,1.091226,0.935653,1.142693
min,1.000000,28.000000,0.000000,0.000000,60.000000,-2.600000,0.000000,0.000000
25%,230.750000,47.000000,120.000000,175.000000,120.000000,0.000000,0.000000,0.000000
50%,460.500000,54.000000,130.000000,223.000000,140.000000,0.500000,0.000000,1.000000
75%,690.250000,60.000000,140.000000,268.000000,157.000000,1.500000,1.000000,2.000000
max,920.000000,77.000000,200.000000,603.000000,202.000000,6.200000,3.000000,4.000000

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
915    False
916    False
917    False
918    False
919    False
Length: 920, dtype: bool

In [14]:
df.isnull().sum()

id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [31]:
new_df = df.fillna(method="ffill")
print(new_df)

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df1 = pd.read_csv(r"C:\Users\abish\Downloads\diabetes.csv")
df1.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [25]:
df1.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    str
 3   dataset   920 non-null    str
 4   cp        920 non-null    str
 5   trestbps  920 non-null    float64
 6   chol      920 non-null    float64
 7   fbs       920 non-null    object
 8   restecg   918 non-null    str
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    str
 13  ca        309 non-null    float64
 14  thal      434 non-null    str
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(2), str(6)
memory usage: 115.1+ KB

In [27]:
df.describe()

,id,age,trestbps,chol,thalch,oldpeak,ca,num
count,920.000000,920.000000,920.000000,920.000000,865.000000,858.000000,309.000000,920.000000
mean,460.500000,53.510870,123.658696,192.636957,137.545665,0.878788,0.676375,0.995652
std,265.725422,9.424685,37.271507,114.559993,25.926276,1.091226,0.935653,1.142693
min,1.000000,28.000000,0.000000,0.000000,60.000000,-2.600000,0.000000,0.000000
25%,230.750000,47.000000,120.000000,164.000000,120.000000,0.000000,0.000000,0.000000
50%,460.500000,54.000000,130.000000,221.000000,140.000000,0.500000,0.000000,1.000000
75%,690.250000,60.000000,140.000000,267.000000,157.000000,1.500000,1.000000,2.000000
max,920.000000,77.000000,200.000000,603.000000,202.000000,6.200000,3.000000,4.000000

In [28]:
df.duplicated().sum()

np.int64(0)